[workspace]
members = [
  "tarefa_1",
  "tarefa_2", "tarefa_3", "tarefa_4",
]

[package]
name = "tarefas_rust"
version.workspace = true
edition = "2021"

[workspace.package]
version = "1.2.0"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"

[dependencies]

